apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodocker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellodocker
  template:
    metadata:
      labels:
        app: hellodocker
    spec:
      containers:
      - name: hellodocker
        image: iborroel/hellodocker
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hellodocker-service
spec:
  type: NodePort
  selector:
    app: hellodocker
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
